### ISSUE TITLE
Project Stability Question

### ISSUE THREAD

**Issue by jameschensmith** [zalando/problem#211]
In short, I would like to kindly/honestly ask if both [Problem](https://github.com/zalando/problem) and it's Spring-related library [Problems for Spring](https://github.com/zalando/problem-spring-web) should be listed as sustained. According to [the link referenced in the stability badge](https://masterminds.github.io/stability/sustained.html), a sustained project should include all of the following:

* At least one stable release (>= 1.0.0)
* Feature complete
* Emphasis may be on maintenance and bug fixing, with few features
* Work on this project may be slow
* Because the project is considered complete and stable, maintainers may not be highly active. Expect some delays in the issue queue.

These guidelines consider a project feature complete, mature, and ready for production use. I recently decided to include this library for some enterprise solutions, but there are a few concerns I have which may lead me to backing out of my decision.

My biggest concern would be the lack of releases. The libraries are going through regular commits (💯❗), but the versions are stuck in the past. For the core problem library, it has been 26 commits (which include version bumps; a great way to avoid vulnerabilities). For the Spring library, it has been **179 commits**.

One more concern I would like to bring up would be responsiveness of the maintainers. Roughly a week ago, I created [an issue in the Spring library](https://github.com/zalando/problem-spring-web/issues/501). I have yet to hear from the maintainers. Now, I do understand that there can be some delays in responses, but combined with the lack of releases, it raises a concern if the issues will never be addressed, and the project never released again.

I hope you take these concerns as passionate criticism, and not as a rant. I love the problem specification! I would also love to see the spec grow out of just being a proposal in the future. I may be in the wrong here, so please correct me if I am. Looking forward to any responses from the team.

**Comment by whiskeysierra** [comment]
> I hope you take these concerns as passionate criticism, and not as a rant.

We're happy to receive feedback and will accept it as such.

Let me try to address your concerns:

> These guidelines consider a project feature complete, mature, and ready for production use.

This project just celebrated its 5th anniversary (🍰 🎉 ) and is in use at hundreds of microservices within Zalando ever since. Out in the open, the most dominant use is probably [JHipster](https://www.jhipster.tech/) which uses problem-spring-web and therefore problem transitively.

From my understanding, we meet all three requirements.

> At least one stable release (>= 1.0.0)

Seems like we ended up with another case of [0-based Versioning](https://0ver.org/), since we're still at 0.x...
I guess a 1.x is long overdue by now and we should do that, rather soon-ish.

> For the core problem library, it has been 26 commits (which include version bumps; a great way to avoid vulnerabilities).

26 commits is technically right, but a bit misleading. Half of all commits are merges and the commit immediately following the latest release is one that bumps the version to the next snapshot. That leaves us with the following version bumps:

```bash
git log 0.24.0...HEAD --oneline --no-merges | grep Bump | cut -d' ' -f3 | sort | uniq -c | sort -r
   5 mockito-core
   2 junit-jupiter.version
   2 dependency-check-maven
   1 versions-maven-plugin
   1 maven-resources-plugin
   1 maven-javadoc-plugin
```

Mockito and JUnit are just used for tests, the resources and dependency check plugins for builds and the version and javadoc plugins for releases. None of them are actually exposed to users of the library, therefore a release wouldn't be needed.

Granted, the picture looks a lot different for problem-spring-web :disappointed: and it should have been released way more often. Total agreement there.

```bash
git log 0.25.2...HEAD --oneline --no-merges | grep Bump | cut -d' ' -f3 | sort | uniq -c | sort -r
   7 spring.version
   7 spring-boot.version
   6 swagger-request-validator-springmvc
   6 mockito-core
   6 jackson.version
   5 tomcat-embed-el
   5 spring-security.version
   4 hibernate-validator
   4 failsafe
   4 dependency-check-maven
   3 junit-jupiter.version
   2 maven-source-plugin
   2 guava
   1 spring-security-oauth2
   1 slf4j.version
   1 slf4j-ext
   1 slf4j-api
   1 problem.version
   1 maven-javadoc-plugin
   1 maven-enforcer-plugin
   1 lombok
   1 jcl-over-slf4j
   1 duplicate-finder-maven-plugin
```

> One more concern I would like to bring up would be responsiveness of the maintainers. 

I came up with the idea for problem and problem-spring-web 5 years ago and I was the main contributor/maintainer ever since. I have switched jobs since, but I'm still trying to maintain those libraries, but obviously with less time at my hands now. That is not meant as an excuse, just trying to explain the organizational side. Problem and problem-spring-web are, to some degree, victims of their own success. Seems like they do their work, provide the value that they promised and for the most part, just work. Hence there is very little interest and activity around them.

> Roughly a week ago, I created [an issue in the Spring library](https://github.com/zalando/problem-spring-web/issues/501). I have yet to hear from the maintainers.

With an effective number of contributors it's not uncommon to have delays, especially if we're talking about a week. I'll be off vacation in two weeks, but I'll try to address that issue before then.

**Comment by whiskeysierra** [comment]
I made a normal release in both, problem and problem-spring-web to have a release with the latest versions.

Problem, in addition received a new release candidate, 0.26.0-RC.0 which introduces Java 9 support (module info).

**Comment by whiskeysierra** [comment]
I'll close this for now and continue focusing on a 1.x release (for both libraries) and the open issue with the 3 unexpected behaviors.
