### ISSUE TITLE
Micronaut Problem Integration

### ISSUE THREAD

**Issue by sdelamo** [zalando/problem#272]
I am a core contributor of the JVM framework [Micronaut](https://micronaut.io). In the latest versions of Micronaut, it is possible to  provide a custom error response processor to respond Problem. 

I have seen you host already integration with Spring:

https://github.com/zalando/problem-spring-web

Would you be interested in hosting/distributing the integration of Zalando's Problem and  Micronaut as well?  I could contribute the implementation.

**Comment by whiskeysierra** [comment]
I'm no longer with Zalando, so I can't help with hosting a new, top-level repository within the `zalando` org.
Since it doesn't fit into `problem` nor `problem-spring-web`, I'd suggest to host it on your personal github account.

I'd be more than happy in promoting this, both in here as well as over at `problem-spring-web`.
