### ISSUE TITLE
Why doesn't have ThrowableProblem default implementations for all methods?

### ISSUE THREAD

**Issue by lathspell** [zalando/problem#42]
I'm not sure how it's intended to create Exceptions that wrap "Problem"s. This is how I got your code working:

`    public final class OutOfStockProblem extends ThrowableProblem {

        private String title;

        public OutOfStockProblem(String title) {
            this.title = title;
        }

        @Override
        public URI getType() {
            return URI.create("http://example.com/out-of-stock");
        }

        @Override
        public String getTitle() {
            return title;
        }

        @Override
        public Response.StatusType getStatus() {
            return BAD_REQUEST;
        }

    }`

But this is how I'd had liked it:

    public final class OutOfStockProblem extends ThrowableProblem {
        public OutOfStockProblem(String title) {
            super(BAD_REQUEST, title, "http://example.com/api-errors/out-of-stock");
        }
    }

That would require additional constructors in ThrowableProblem and default implementations of the three getter but looks much cleaner. Why does ThrowableProblem have to be abstract?

**Comment by whiskeysierra** [comment]
I'm answering the questions in a specific order that for me would make the most sense to a reader:

> Why does ThrowableProblem have to be abstract?

Because it's explicitly designed to be subclassed, not instantiated. Having a class to both make for a fragile class design, because you always have to keep two very distinct types of users in mind: sub classes and direct instantiators. I prefer every class to be either abstract or final, nothing in between.

> That would require additional constructors in ThrowableProblem and default implementations of the three getter but looks much cleaner.

Having to subclass a type that has a mandatory non-default constructor is very limiting. As an implementor you're required to invoke the super constructor as the very first statement of your own constructor. This does not allow to defer *computation* of values until the corresponding accessor method is actually used. Compare e.g. FilterInputStream (old way of using a constructor) with Guava's ForwardingObject (abstract method to access instance). Implementing methods is longer (granted, more boilerplate code) but it gives implementors a lot more freedom in how they want to structure their classes/code. 

What I could imagine though is a seperate class, e.g. `SimpleThrowableProblem`?, that offers the default implementation for the accessor methods with a 3-argument constructor (class should still be abstract though).
