### ISSUE TITLE
Add valueof in StatusType

### ISSUE THREAD

**Issue by andreabreu-me** [zalando/problem#56]
It would be nice to implement this method in Status enum. Right now, mapping from others status enums is not very friendly (like mapping from HttpStatus from Spring to StatusType).

`Status.valueOf(HttpStatus.NO_CONTENT.value())`

**Comment by whiskeysierra** [comment]
`Status` doesn't contain every single possible HTTP status, since it's an open-ended list of values. That's the reason why we have the interface `StatusType`. If you want to translate from Spring's `HttpStatus` to `StatusType`, then you should implement the interface within an adapter class, like in [problem-spring-web](https://github.com/zalando/problem-spring-web/blob/master/src/main/java/org/zalando/problem/spring/web/advice/HttpStatusAdapter.java):

```java
/**
 * An implementation of {@link StatusType} to map {@link HttpStatus}.
 */
public class HttpStatusAdapter implements StatusType {

    private final HttpStatus status;

    public HttpStatusAdapter(final HttpStatus status) {
        this.status = status;
    }

    @Override
    public int getStatusCode() {
        return status.value();
    }

    @Override
    public String getReasonPhrase() {
        return status.getReasonPhrase();
    }

    @Override
    public boolean equals(final Object that) {
        if (this == that) {
            return true;
        } else if (that instanceof HttpStatusAdapter) {
            final HttpStatusAdapter other = (HttpStatusAdapter) that;
            return Objects.equals(status, other.status);
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(status);
    }

}
```

**Comment by andreabreu-me** [comment]
@whiskeysierra Wow. This way makes a lot of sense. Thank you.
